ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.telegram.plugins.HttpKt.configureHttp
      - com.telegram.plugins.RoutingKt.configureRouting
      - com.telegram.plugins.OpenApiKt.configureOpenApi
      - com.telegram.plugins.TdLightKt.configureTdLight
